### ISSUE TITLE
outline colour

### ISSUE THREAD

**Issue by guer0125** [guer0125/arrrgenes-treasure-tours#1]
Markbot is saying that the colour of the outline doesn't have enough contrast. i tried white and black. but i also don't know if i am doing it right

i added

.nav a:focus {
outline: 3px solid #000;
}

@muxlowc

**Comment by muxlowc** [comment]
@guer0125  So two things I think you might need:

1) You'll need to add a background colour to your banner (so that in case your image breaks, you still have a brown background (rather than it being white, with white text on it = not accessible)

.banner {
  min-height: 16em;
  background-color: #704c2a;
  color: #fff;
}

2) You actually need to add an "outine-color:" 

.nav a:focus {
  outline-color: #fff;
}

Hope this helps!
